repository: dddyom/dddyom.github.io
favicon: images/favicon.ico
version: 2
name: Данил Дёмин
title: Python Developer
email: dddyom@gmail.com
darkmode: never
github_username: dddyom
linkedin_username: dddyom
additional_links:
  - title: telegram
    icon: fab fa-telegram
    url: "https://telegram.me/dddyom"

about_title: About
about_content: |

  Uot tak uot

content:
  - title: SKILLS
    layout: list
    content:
      - layout: left
        title: Web-development
        description: |
          - Python, OOP, REST API
          - JS, JQuery, Semantic UI, DevExpress
          - Django, Django Rest Framework, Flask
          - PostgreSQL, MySQL, Ms SQL
          - HTML, CSS, Markdown
          - Selenium, BeautifulSoup
          - requests, logging, loguru

      - layout: left
        title: Linux
        description: |
          - bash, zsh, systemd
          - Docker, Nginx
          - Git, pip, conda, jupyter
          - Vim, tmux, i3wm (arch linux)

      - layout: left
        title: Machine Learning
        description: |
          - yolov5, detectron
          - tensorflow

      - layout: left
        title: Data processing
        description: |
          - numpy, pandas, matplotlib

  - title: Projects
    layout: list
    content:
      - layout: left
        title: TargetDetection
        link: github.com/dddyom/TargetDetection
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/dddyom/TargetDetection
        description: |
          Поиск целей на буфере радиолокатора нейросетью

  - title: Education
    layout: list
    content:
      - layout: left
        title: "Moscow Polytech, Moscow, Russia"
        caption: 2018 - 2022
        sub_title: Автоматизированные системы обработки информации и управления
        description: |
          В качестве ключевых работ, написал и успешно защитил ряд проектов в разных областях: от реализаций базовых академических алгоритмов, до проектов в области веб-разработки и в машинном обучении.

  - title: About more
    layout: text
    content: |
      - пунктикк
footer_show_references: false
plugins:
  - jekyll-seo-tag

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed
