repository: dddyom/dddyom.github.io
favicon: images/favicon.ico
version: 2
name: Данил Дёмин
title: Python Developer
email: dddyom@gmail.com
darkmode: never
github_username: dddyom
linkedin_username: dddyom
youtube_username: globalmtb
additional_links:
  - title: telegram
    icon: fab fa-telegram
    url: 'https://telegram.me/dddyom'
content:
  - content:
      - description: |
          - Python, OOP, REST API
          - Django, Django Rest Framework
          - PostgreSQL, MySQL
          - HTML, CSS, Markdown
          - Selenium, BeautifulSoup
          - requests, logging, loguru
        layout: left
        title: Web-development
      - description: |
          - bash, zsh, systemd
          - Docker, Nginx
          - Git, pip, conda, jupyter
          - Vim, tmux, i3wm (arch linux)
        layout: left
        title: Linux
      - description: |
          - yolov5, detectron
          - tensorflow
        layout: left
        title: Machine Learning
      - description: |
          - numpy, pandas, matplotlib
        layout: left
        title: Data processing


      - title: SKILLS
        layout: list
        content:
        additional_links:
          - icon: fab fa-github
            title: github
            url: github.com/dddyom/TargetDetection
        description: |
          Поиск целей на буфере радиолокатора нейросетью

          # 2
        layout: left
        link: github.com/dddyom/TargetDetection
        title: TargetDetection
      - additional_links:
          - icon: fab fa-github
            title: github
            url: github.com/dddyom/drf-notes
        description: |
          CRUD API для приложения с заметками

          # 3
        layout: left
        link: github.com/dddyom/drf-notes
        title: drf-notes
      - additional_links:
          - icon: fab fa-github
            title: github
            url: github.com/dddyom/ipc_detector_app
        description: >
          IPC-модуль на сокетах с docker на сервере для поиска образов
          радиосигнала нейросетью


          # 4
        layout: left
        link: github.com/dddyom/ipc_detector_app
        title: IPC-Detector-app
      - additional_links:
          - icon: fab fa-github
            title: github
            url: github.com/dddyom/online_store
        description: |
          Веб-приложение для магазина

          # 5
        layout: left
        link: github.com/dddyom/ipc_detector_app
        title: online-store
      - additional_links:
          - icon: fab fa-github
            title: github
            url: github.com/dddyom/parser
        description: |
          Парсер сайта о картинах, собирающий данные для обучения нейросети

          # 6
        layout: left
        link: github.com/dddyom/parser
        title: parser
      - additional_links:
          - icon: fab fa-github
            title: github
            url: github.com/dddyom/dataset_maker
        description: |
          Обработчик буферов радиолокатора для сбора данных, обучающих нейросеть
        layout: left
        link: github.com/dddyom/dataset_maker
        title: Dataset-maker
    layout: list
    title: Projects
  - content:
      - caption: Nov 20 - Aug 22
        description: >
          Занимался сбором данных, обучением на них нейросетей поиску
          пользовательнских объектов, и их внедрением в продукт предприятия.
        layout: left
        sub_title: Python Developer
        title: 'ТОО "СКТБ "Гранит", Almaty'
    layout: list
    title: Experience
  - content:
      - caption: 2018 - 2022
        description: >
          В качестве ключевых работ, написал и успешно защитил ряд проектов в
          разных областях: от реализаций базовых академических алгоритмов, до
          проектов в области веб-разработки и в машинном обучении.
        layout: left
        sub_title: Автоматизированные системы обработки информации и управления
        title: 'Moscow Polytech, Moscow, Russia'
    layout: list
    title: Education
  - content: >
      - Кроме указанных выше технологий работал и базово знаком с
      <mark>Golang</mark>
        , <mark>C++</mark>
        , <mark>JavaScript</mark>
        , <mark>React</mark>
        , <mark>Figma</mark>
        , <mark>LaTex</mark>.
      - Могу водить машину, есть права категории <mark>БЭ</mark>.

      - Играю на <mark>гитаре</mark> и в <mark>шахматы</mark>.

      - Добрый, спокойный и <mark>ответственный</mark>:).
    layout: text
    title: About
footer_show_references: false
plugins:
  - jekyll-seo-tag
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
