# Site
repository: dddyom/dddyom.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Данил Дёмин 
title: Python Developer
email: dddyom@gmail.com
#website: www.github.com/dddyom

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username: dddyom
# stackoverflow_username: "00000001"
linkedin_username: dddyom
youtube_username: globalmtb
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: telegram
  icon: fab fa-telegram
  url: https://telegram.me/dddyom

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
#about_content: | # this will include new lines to allow paragraphs
  #Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  #I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
 - title: SKILLS
    layout: list
    content:
      - layout: left
        title: Web-development
        description: |
          - Python, OOP, REST API
          - Django, Django Rest Framework
          - PostgreSQL, MySQL
          - HTML, CSS, Markdown
          - Selenium, BeautifulSoup
          - requests, logging, loguru
      - layout: left
        title: Linux
        description: |
           - bash, zsh, systemd
           - Docker, Nginx
           - Git, pip, conda, jupyter
           - Vim, tmux, i3wm (arch linux)
      - layout: left
        title: Machine Learning
        description: |
           - yolov5, detectron
           - tensorflow

      - layout: left
        title: Data processing
        description: |
           - numpy, pandas, matplotlib


  - title: Projects 
    layout: list 

    content:
      # 1
      - layout: left
        title: Targetdetection
        link: github.com/dddyom/TargetDetection
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/dddyom/TargetDetection
        description: |
          Поиск целей на буфере радиолокатора нейросетью

      # 2
      - layout: left
        title: drf-notes
        link: github.com/dddyom/drf-notes
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/dddyom/drf-notes
        description: |
          CRUD API для приложения с заметками

      # 3
      - layout: left
        title: IPC-Detector-app
        link: github.com/dddyom/ipc_detector_app
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/dddyom/ipc_detector_app
        description: |
          IPC-модуль на сокетах с docker на сервере для поиска образов радиосигнала нейросетью

      # 4
      - layout: left
        title: online-store
        link: github.com/dddyom/ipc_detector_app
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/dddyom/online_store
        description: |
          Веб-приложение для магазина

      # 5
      - layout: left
        title: parser
        link: github.com/dddyom/parser
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/dddyom/parser
        description: |
          Парсер сайта о картинах, собирающий данные для обучения нейросети

      # 6
      - layout: left
        title: Dataset-maker
        link: github.com/dddyom/dataset_maker
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/dddyom/dataset_maker
        description: | 
          Обработчик буферов радиолокатора для сбора данных, обучающих нейросеть

  - title: Experience 
    layout: list 
    content:
      - layout: left
        title: ТОО "СКТБ "Гранит", Almaty 
        sub_title: Python Developer
        caption: Nov 20 - Aug 22 
        description: | 
          Занимался сбором данных, обучением на них нейросетей поиску пользовательнских объектов, и их внедрением в продукт предприятия.

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: Moscow Polytech, Moscow, Russia
        caption: 2018 - 2022
        sub_title: Автоматизированные системы обработки информации и управления
        description: | В качестве ключевых работ, написал и успешно защитил ряд проектов в разных областях: от реализаций базовых академических алгоритмов, до проектов в области веб-разработки и в машинном обучении.

  - title: About
    layout: text
    content: | 
      - Кроме указанных выше технологий работал и базово знаком с <mark>Golang</mark>
, <mark>C++</mark>
, <mark>JavaScript</mark>
, <mark>React</mark>
, <mark>Figma</mark>
, <mark>LaTex</mark>.
      - Могу водить машину, есть права категории <mark>БЭ</mark>.
      - Играю на <mark>гитаре</mark> и в <mark>шахматы</mark>.
      - Добрый, спокойный и <mark>ответственный</mark>:).

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
